apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-template
  namespace: shani1
spec:
  entrypoint: hello
  templates:
    - name: hello
      container:
        image: alpine
        command: [sh, -c]
        args: ["echo hello world"]