apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app4-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: app-of-apps4/apps/app1
    repoURL: 'https://github.com/shanioren/argo-test.git'
    targetRevision: main
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
